"""add grade

Revision ID: 53eb931714f7
Revises: 14f5232e288d
Create Date: 2024-06-13 11:10:32.516970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eb931714f7'
down_revision = '14f5232e288d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_jury_composition', 'jury', ['president_id', 'examinateur_id', 'rapporteur_id'], schema='public')
    op.drop_constraint('jury_examinateur_id_fkey', 'jury', type_='foreignkey')
    op.drop_constraint('jury_rapporteur_id_fkey', 'jury', type_='foreignkey')
    op.drop_constraint('jury_president_id_fkey', 'jury', type_='foreignkey')
    op.create_foreign_key(None, 'jury', 'enseignant', ['examinateur_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'jury', 'enseignant', ['president_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'jury', 'enseignant', ['rapporteur_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.create_foreign_key('jury_president_id_fkey', 'jury', 'enseignant', ['president_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jury_rapporteur_id_fkey', 'jury', 'enseignant', ['rapporteur_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jury_examinateur_id_fkey', 'jury', 'enseignant', ['examinateur_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_jury_composition', 'jury', schema='public', type_='unique')
    op.drop_table('grade')
    # ### end Alembic commands ###
