"""add grades

Revision ID: 73be087b115e
Revises: 53eb931714f7
Create Date: 2024-06-13 11:21:03.776488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73be087b115e'
down_revision = '53eb931714f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enseignant', sa.Column('grade_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enseignant', 'grade', ['grade_id'], ['id'], ondelete='CASCADE')
    op.drop_column('enseignant', 'grade')
    op.drop_constraint('jury_examinateur_id_fkey', 'jury', type_='foreignkey')
    op.drop_constraint('jury_president_id_fkey', 'jury', type_='foreignkey')
    op.drop_constraint('jury_rapporteur_id_fkey', 'jury', type_='foreignkey')
    op.create_foreign_key(None, 'jury', 'enseignant', ['examinateur_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'jury', 'enseignant', ['president_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'jury', 'enseignant', ['rapporteur_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'jury', schema='public', type_='foreignkey')
    op.create_foreign_key('jury_rapporteur_id_fkey', 'jury', 'enseignant', ['rapporteur_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jury_president_id_fkey', 'jury', 'enseignant', ['president_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('jury_examinateur_id_fkey', 'jury', 'enseignant', ['examinateur_id'], ['id'], ondelete='CASCADE')
    op.add_column('enseignant', sa.Column('grade', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enseignant', type_='foreignkey')
    op.drop_column('enseignant', 'grade_id')
    # ### end Alembic commands ###
